### ISSUE TITLE
api signature 不通 气死啦

### ISSUE THREAD

**Issue by cycmay** [KKCoinEx/api-wiki#1]
b'{"message":"Signature verification failed.","status_code":487}'

**Comment by samyn** [comment]
能简单描述一下您现在完成的步骤吗？

**Comment by cycmay** [comment]
def signature(self, message):
        # 从PEM文件中读取私钥数据
        key_file = open('private.pem', 'rb')
        key_data = key_file.read()
        key_file.close()

        password = bytes('密码', encoding="utf-8")
        key = load_privatekey(FILETYPE_PEM, key_data, passphrase=password)
        content = message

        dig = sign(key, content, 'sha256')  # d为经过SHA1算法进行摘要、使用私钥进行签名之后的数据
        print(base64.b64encode(dig))
        signature = base64.b64encode(dig).decode() # 将d转换为BASE64的格式

**Comment by cycmay** [comment]
请问有python的demo吗

**Comment by samyn** [comment]
抱歉，暂时没有，只有node和php的，原理并不复杂，打包参数时注意一下顺序就行了

**Comment by cycmay** [comment]
请问，为什么我在本地请求的响应时间总是超时呢？你们那边测试没有问题吗？

**Comment by cycmay** [comment]
还有，请问打包的时候，endpoint{"id":"923459920"}timestamp 这个参数里面的空格一定要去掉吗？
